// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Calc: typeof import('./src/components/Calc.vue')['default']
    CalcContainer: typeof import('./src/components/CalcContainer.vue')['default']
    CalcInput: typeof import('./src/components/CalcInput.vue')['default']
    Chart: typeof import('./src/components/Chart.vue')['default']
    CoordCard: typeof import('./src/components/coordCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    MoonCard: typeof import('./src/components/moonCard.vue')['default']
    MoonCardSkeleton: typeof import('./src/components/MoonCardSkeleton.vue')['default']
    PlanetsCard: typeof import('./src/components/PlanetsCard.vue')['default']
    PlanetsCardSkeleton: typeof import('./src/components/PlanetsCardSkeleton.vue')['default']
    Refresher: typeof import('./src/components/Refresher.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeeingTable: typeof import('./src/components/SeeingTable.vue')['default']
    SolarSystemCharts: typeof import('./src/components/SolarSystemCharts.vue')['default']
    SolarSystemChartsSkeleton: typeof import('./src/components/SolarSystemChartsSkeleton.vue')['default']
    SunCard: typeof import('./src/components/sunCard.vue')['default']
    SunCardSkeleton: typeof import('./src/components/SunCardSkeleton.vue')['default']
    WeatherCard: typeof import('./src/components/WeatherCard.vue')['default']
  }
}
