// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CoordCard: typeof import('./src/components/coordCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonButton: typeof import('@ionic/vue')['IonButton']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    MoonCard: typeof import('./src/components/moonCard.vue')['default']
    MoonCardSkeleton: typeof import('./src/components/MoonCardSkeleton.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    SunCard: typeof import('./src/components/sunCard.vue')['default']
    SunCardSkeleton: typeof import('./src/components/SunCardSkeleton.vue')['default']
    WeatherCard: typeof import('./src/components/WeatherCard.vue')['default']
  }
}

export { }
