// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    CoordCard: typeof import('./src/components/coordCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    'IIon:cogOutline': typeof import('~icons/ion/cog-outline')['default']
    'IIon:logoGithub': typeof import('~icons/ion/logo-github')['default']
    'IIon:menu': typeof import('~icons/ion/menu')['default']
    'IIon:telescopeOutline': typeof import('~icons/ion/telescope-outline')['default']
    IonApp: typeof import('@ionic/vue')['IonApp']
    IonButtons: typeof import('@ionic/vue')['IonButtons']
    IonCard: typeof import('@ionic/vue')['IonCard']
    IonCardContent: typeof import('@ionic/vue')['IonCardContent']
    IonCardHeader: typeof import('@ionic/vue')['IonCardHeader']
    IonCardSubtitle: typeof import('@ionic/vue')['IonCardSubtitle']
    IonCardTitle: typeof import('@ionic/vue')['IonCardTitle']
    IonContent: typeof import('@ionic/vue')['IonContent']
    IonFooter: typeof import('@ionic/vue')['IonFooter']
    IonHeader: typeof import('@ionic/vue')['IonHeader']
    IonItem: typeof import('@ionic/vue')['IonItem']
    IonList: typeof import('@ionic/vue')['IonList']
    IonMenu: typeof import('@ionic/vue')['IonMenu']
    IonMenuButton: typeof import('@ionic/vue')['IonMenuButton']
    IonMenuToggle: typeof import('@ionic/vue')['IonMenuToggle']
    IonPage: typeof import('@ionic/vue')['IonPage']
    IonRouterOutlet: typeof import('@ionic/vue')['IonRouterOutlet']
    IonSplitPane: typeof import('@ionic/vue')['IonSplitPane']
    IonTitle: typeof import('@ionic/vue')['IonTitle']
    IonToolbar: typeof import('@ionic/vue')['IonToolbar']
    MoonCard: typeof import('./src/components/moonCard.vue')['default']
    MoonCardSkeleton: typeof import('./src/components/MoonCardSkeleton.vue')['default']
    ReloadPrompt: typeof import('./src/components/ReloadPrompt.vue')['default']
    SunCard: typeof import('./src/components/sunCard.vue')['default']
    SunCardSkeleton: typeof import('./src/components/SunCardSkeleton.vue')['default']
    WeatherCard: typeof import('./src/components/WeatherCard.vue')['default']
  }
}

export { }
